### ISSUE TITLE
Sobre ejercicio CRUD

### ISSUE THREAD

**Issue by Makova** [deepb/crud#1]
Hola @deepb Voy viendo los nuevos commit que haces y como te he dicho en el curso, deberías de corregir la línea 118 que falla a la salida de la ventana glade:

```
File "crud.py", line 118, in cursorDB
    return self._db.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
```

por lo demás todo funciona correctamente. Excelente ejercicio.

**Comment by deepb** [comment]
No encuentro el fallo:

¿Puedes hacer un `print self._db` en la L110?

A mi me funciona perfectamente.

**Comment by Makova** [comment]
Ok 👍

**Comment by deepb** [comment]
Ya le encontre el fallo.

Muy bien, profesor.
Ahora lo cambio.
